services:
  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    ports:
      - "9100:9100"

  promtail:
    image: grafana/promtail:2.8.0
    container_name: promtail
    volumes:
      - /home/peter/logs:/var/log/fastapi
      - ./promtail.yml:/etc/promtail/config.yml
      - ./positions:/var/log/loki
    command: -config.file=/etc/promtail/config.yml